import Head from 'next/head'
import Header from '../../Component/Header'
import Categories from '../../Component/Categories'
import Banner from '../../Component/Banner'
import Vente from '../../Component/TopVente/Vente'
import Pub from '../../Component/Pub'
import Produit from '../../Component/Produit/Produit'
import Navbar from '../../Layouts/Navbar'
import { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import { AllProduits } from '../../Reducer/produitReducer'
import axios from 'axios'
import Loading from '../../Component/Loading'

export default function Home({produits}) {
  const dispatch = useDispatch()

  useEffect(() => {
      dispatch(AllProduits(produits))
  }, [dispatch])

  if(!produits) {

    return <Loading />
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <Header />
          <Categories />
          <Banner />
          <Vente />
          <Pub />
          <Produit />
        </section>
        <article>
          <Navbar />
        </article>
      </main>
      
    </>
  )
}

export async function loadProduits() {

  const response = await axios.get('http://192.168.1.11:8000/api/produits');
  return response
}

export async function getStaticProps() {
  // code
  const res  = await loadProduits()
  const data = res.data.data

  return {
    props: {
        produits: data
    },
  }
}
