import Head from 'next/head'
import Header from '../../Component/Header'
import Categories from '../../Component/Categories'
import Banner from '../../Component/Banner'
import Vente from '../../Component/TopVente/Vente'
import Pub from '../../Component/Pub'
import Produit from '../../Component/Produit/Produit'
import Navbar from '../../Layouts/Navbar'
import { useViewportSize } from '@mantine/hooks';
import axios from 'axios'
import Loading from '../../Component/Loading'

export default function Home({produits, categories}) {

      if(!produits || !categories) {

        return <Loading />
      }
      const { width } = useViewportSize();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <Header />
          <Categories categories={categories} />
          <Banner />
          <Vente produits={produits} />
          <Pub />
          <Produit produits={produits} />
        </section>
        {
          width <= 1200 && 
            <article>
              <Navbar />
            </article>
        }
      </main>
      
    </>
  )
}

export async function loadProduits() {

  const response = await axios.get(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/produits`);
  return response
}

export async function loadCategories() {
  const response = await axios.get(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/categories`);
  return response
}

export async function getStaticProps() {
  // code
  const res  = await loadProduits()
  const cat = await loadCategories()

  return {
    props: {
        produits: res.data.data,
        categories: cat.data.data
    },
  }
}
